#page title
page_title                                :  Mevenus - Book Fast, Beauty Now                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app_icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Mevenus                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Book Fast, Beauty Now

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Mevenus Team                     
your_link                                 : https://mevenus.com
your_city                                 : Ha Noi, Vietnam
email_address                             : mevenus@gmail.com
facebook_username                         : mevenus                                     
instagram_username                        : mevenus
twitter_username                          : mevenus
github_username                           : mevenus
youtube_username                          : mevenus



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Đặt lịch dễ dàng
    description                           : Chỉ bằng một vài thao tác bạn có thể đặt lịch làm đẹp tại các chi nhánh của các trung tâm.
    fontawesome_icon_name                 : magic
    
  - title                                 : Đánh giá thông minh
    description                           : Dựa vào các đánh giá của các khách hàng đã dùng dịch vụ để đưa ra quyết định trước khi đặt lịch sử dụng dịch vụ.
    fontawesome_icon_name                 : magic

  - title                                 : Quản lý lịch trực quan
    description                           : Hiển thị và nhắc nhở cho các lịch làm đẹp sắp tới cho bạn.
    fontawesome_icon_name                 : magic

  - title                                 : Quản lý khách hàng
    description                           : Bạn là chủ cửa hàng, bạn muốn quản lý các khác hàng một cách hiệu quản. Mevenus sẽ đem lại điều này chỉ bằng một vài thao tác.
    fontawesome_icon_name                 : magic
    
  - title                                 : Tìm kiếm thương hiệu
    description                           : Hiển thị các thương hiệu và các chi nhánh trên bản đồ. Giúp bạn tiết kiệm thời gian đi tìm kiếm một cơ sở làm đẹp ưng ý.
    fontawesome_icon_name                 : magic

  - title                                 : Chia sẻ làm đẹp
    description                           : Là nơi lắng nghe và chia sẻ các kinh nghiệm làm đẹp. Giúp bạn không phải tìm kiếm trên các nguồn khác nhau.
    fontawesome_icon_name                 : magic
    
# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : coral                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
